
var Dashboard = "Gauges show the % of compliant campaigns within that Business Area Group.  Example, if within Rail there are 50 campaigns in the selected date range (after exclusions, see below), and 49 of them are compliant then the compliance value is 98% (49 is 98% of 50).\n\n All graphs exclude values from manually scheduled players including:\n Digital Escalator Panels\nHEX Motion\n Old St Roundabout\n Cromwell Road\n Heathrow DAPS Pack A and B\n Heathrow Gateroom DAPS\n\n Compliance Definition:\n A player for a campaign is considered compliant if it has played 95% or more of what was booked for every hour it has been scheduled\n A campaign is considered compliant if ALL players have played 95% or better of what was booked for every hour it has been scheduled.  Compliance definition has been determined by UK IT team.\n\n Data manipulation:\n Edinburgh Princes St D6s – slave data is discarded and data from master players is shown instead due to an issue with BroadSign not recording successful playout from slaves due to playout aborted message.\n A40 Spire – one player, two frames.  If 20% SOT is booked and played, playout report shows 40% and 0%.  Playout data is split across both frames. \n\nWaterloo Transvision – one player, two screens.  If 20% SOT is booked and played, playout report shows 20% and 0%.  Playout data is copied from one to the other.  Second screen is getting a separate player in Feb 2017 so this data manipulation will be removed.\n\n NOTE:\n The comparison is for what was played vs what was booked.  If a campaign was not booked for an hour but still played, this will not show up in application.  Item has been logged on the backlog to include plays that were not booked." ;

var frame_CampaignInformation ="This graph shows the percentage of frames in a campaign that meet the compliance threshold.\n\n Example:\n If a campaign has 100 frames, and 50% of them meet the definition of compliance, this graph will show 50%.\n\n All (100% of) frames must meet the compliance threshold for the campaign to be determined to be compliant.\n\n If all frames are compliant, the campaign will be coloured blue and the value shown will be 100%\n\n If less than all frames are compliant, the campaign will be coloured red and the value shown will be less than 100%\n";

var sot_CampaignInformation ="This graph shows the performance of a campaign.\n\n Example:\n If a campaign was booked for 20,000 seconds of play within the selected date range and plays out 22,000 seconds it will show 110% (22,000 is 110% of 20,000).\n\n If all players play 95% or more of what was booked for that campaign (in the selected date range) for all hours then the campaign is compliant and is coloured blue.\n\n If one or more players played less than 95% of what was booked for that campaign in one or more hours, the campaign is non-compliant and coloured red.\n";

var frame_PlayerInformation = "This graph shows the percentage of days in a campaign that meet the compliance threshold for that player, with the selected date range.\n\n Example:\n Date range for 5 days is selected.\n\n Campaign is selected in the Campaign Chart (title: % frame above threshold) that has 20 frames.\n\n All 20 players are returned in this chart.\n\n If a player is compliant for all hours for five days for this campaign (i.e. played out 95% or more of what was booked) then it is 100% compliant for all days, and a value of 100% is shown.\n\n If a player is non-compliant for 1 hour on 2 days, then it is compliant for 60% of the days and a value of 60% will be shown.\n\n If the value is 100% (i.e. compliant) then it is shown as blue.  If the value is less than 100% (i.e. non-compliant) then it is shown as red. " ;

var sot_PlayerInformation = "This graph shows the performance of a player for a campaign.\n\nExample:\n If a player was booked to play 20,000 seconds for the selected campaign within the selected date range and plays out 22,000 seconds it will show 110% (22,000 is 110% of 20,000).\n\n If the player played 95% or more of what was booked for that campaign (in the selected date range) for all hours then the player is compliant and is coloured blue.\n\n If the player played less than 95% of what was booked for that campaign in one or more hours, the player is non-compliant and coloured red." ;

var frame_DayInformation = "This graph shows the percentage of hours in a campaign that meet the compliance threshold for that player on each day within the selected range.\n\nExample:\n Date range for 5 days is selected.\n Campaign is selected in the Campaign Chart (title: % frame above threshold) that has 20 frames.\n\n A frame is selected.\n\nIn this chart, all days that the campaign was booked on this frame within the selected date range are shown.\n\n If a player is compliant for all hours on a day for this campaign (i.e. played out 95% or more of what was booked) then the day shows 100% compliant.\n\n If a player is compliant for half the hours on a day for this campaign (i.e. played out 95% or more of what was booked) then the day shows 50% compliant.\n\nIf the value is 100% (i.e. compliant) then it is shown as blue.  If the value is less than 100% (i.e. non-compliant) then it is shown as red. " ;

var sot_DayInformation = "This graph shows the performance of a day for a player in a campaign.\n\nExample:\n If a player was booked to play 20,000 seconds in a day for the selected campaign within the selected date range and plays out 22,000 seconds it will show 110% (22,000 is 110% of 20,000).\n\nIf the player played 95% or more of what was booked for that campaign (in the selected date range) for all hours in that day then the player is compliant for that day and the day is coloured blue.\n\n If the player played less than 95% of what was booked for that campaign (in the selected date range) for one or more hours in that day then the player is non-compliant for that day and the day is coloured red." ;

var frame_DateInformation = "This graph shows the percentage of what played to what was booked for every booked hour in a selected day for the selected frame in a selected campaign.\n\n Example:\n Campaign, Player, Day are selected.\n\n Each booked hour (for that day, for that player for that campaign) are shown with a performance value (%played vs booked).\n\n If 20% SOT was booked and 30% played out a value of 150% is shown (30% is 150% of 20%).\n\n If 20% SOT was booked and 10% played out a value of 50% is shown (10% is 50% of 20%).\n\n If the hour shows a value of 95% or more it is compliant and shows blue.\n\n If the hour shows a value of less than 95% it is non-compliant and shows red.";

var sot_DateInformation = "This graph shows the performance of a player in a campaign for each hour of the selected day.\n\n Example:\n If a player was booked to play 500 seconds for the selected campaign within an hour and played out 750 seconds it will show 150% (750 is 150% of 500).\n\n If the player played 95% or more of what was booked for that campaign in that hour then the hour is compliant and is coloured blue.\n\n If the player played less than 95% of what was booked for that campaign in that hour then the hour is non-compliant and is coloured red.";